version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/dbtest
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DRIVER=org.postgresql.Driver
      - JPA_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network
    
  db:
    image: postgres:14-alpine
    container_name: my-postgres
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    