version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dbtest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_DRIVER=org.postgresql.Driver
      - JPA_DDL_AUTO=update
      - VAADIN_SKIP_NODE_MODULES_CLEANING=true
    volumes:
      - ./src:/app/src
      - maven-repo:/root/.m2
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    container_name: my-postgres
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  maven-repo:
    